<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <ProjectReference Include="../../soenneker.culture.english.us/src/Soenneker.Culture.English.US/Soenneker.Culture.English.US.csproj" />
    <ProjectReference Include="../../soenneker.extensions.char/src/Soenneker.Extensions.Char/Soenneker.Extensions.Char.csproj" />
    <ProjectReference Include="../../soenneker.extensions.spans.readonly.bytes/src/Soenneker.Extensions.Spans.Readonly.Bytes/Soenneker.Extensions.Spans.Readonly.Bytes.csproj" />
    <ProjectReference Include="../../soenneker.extensions.spans.readonly.chars/src/Soenneker.Extensions.Spans.Readonly.Chars/Soenneker.Extensions.Spans.Readonly.Chars.csproj" />
    <ProjectReference Include="../../soenneker.extensions.string/src/Soenneker.Extensions.String/Soenneker.Extensions.String.csproj" />
    <ProjectReference Include="../../soenneker.hashing.sha256/src/Soenneker.Hashing.Sha256/Soenneker.Hashing.Sha256.csproj" />
    <ProjectReference Include="../../soenneker.utils.pooledstringbuilders/src/Soenneker.Utils.PooledStringBuilders/Soenneker.Utils.PooledStringBuilders.csproj" />
    <ProjectReference Include="../../soenneker.utils.random/src/Soenneker.Utils.Random/Soenneker.Utils.Random.csproj" />
  </ItemGroup>
</Project>
