"""Recreate pinned comparison sources and opt-in local dependency wiring.

Run from any directory with sibling repositories listed in baseline.json present.
The script never edits production sources or changes repository checkouts.
"""
from pathlib import Path
import json
import subprocess
import xml.etree.ElementTree as ET

audit = Path(__file__).resolve().parent
root = audit.parent.parent
repositories = json.loads((audit / 'baseline.json').read_text())
selected = [name for name in repositories if name not in
            ('Soenneker.Gen.EnumValues', 'Soenneker.Enums.ContentKinds')]

for name in selected:
    info = repositories[name]
    repository = root / info['repository']
    commit = info['commit']
    files = subprocess.check_output(
        ['git', '-C', str(repository), 'ls-tree', '-r', '--name-only', commit, 'src'], text=True).splitlines()
    for file in files:
        if not file.endswith('.cs'):
            continue
        source = subprocess.check_output(
            ['git', '-C', str(repository), 'show', f'{commit}:{file}'], text=True, encoding='utf-8')
        for namespace in sorted(selected, key=len, reverse=True):
            source = source.replace(namespace, 'Baseline.' + namespace)
        target = audit / 'Baseline' / name / file
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(source, encoding='utf-8')

lines = ['<!-- Generated by soenneker.extensions.string/performance/prepare.py -->', '<Project>']
for name, info in repositories.items():
    lines.append(f'  <ItemGroup Condition="\'$(AuditLocalDependencies)\' == \'true\' and \'$(MSBuildProjectName)\' == \'{name}\'">')
    for reference in ET.parse(root / info['project']).iter('PackageReference'):
        dependency = reference.get('Include')
        if dependency not in repositories or dependency == 'Soenneker.Gen.EnumValues':
            continue
        lines.append(f'    <PackageReference Remove="{dependency}" />')
        lines.append(f'    <ProjectReference Include="$(MSBuildThisFileDirectory){repositories[dependency]["project"]}" />')
    lines.append('  </ItemGroup>')
lines.append('</Project>')

# Explicit opt-in is required, and unrelated build configuration is never overwritten.
target = root / 'Audit.Dependencies.targets'
target.write_text('\n'.join(lines) + '\n')
print(f'Prepared pinned baseline sources and {target}')
print('Build with -p:DirectoryBuildTargetsPath=' + str(target))
print('and -p:AuditLocalDependencies=true (or import this file from Directory.Build.targets).')
